### ISSUE TITLE
Testing on real device (iOS - iPad) - device is unavailable

### ISSUE THREAD

**Issue by hinok** [axemclion/browser-perf#22]
Hey,
I want test my SPA on real device - iPad Air, but the problem is that iPad is not an available device in appium.

I copied config from browser-perf repo
```javascript
{
    "selenium": "http://localhost:4723/wd/hub",
	"browsers": [{
		"platformName": "iOS",
		"platformVersion": "8.1.2", // current version of iOS installed on iPad
		"browserName": "Safari",
		"deviceName": "Milosz's iPad", // Name of device, the same name is visible in Xcode
		"autoWebview": true,
		"loggingPrefs": {
			"performance": "ALL"
		}
	}]
}
```

Run:
```
 browser-perf --config-file=configs/ipad.config.json http://localhost:8000/admin/dashboard
```

Result
```
browser-perf --config-file=configs/ipad.config.json http://localhost:8000/admin/dashboard
info: --> POST /wd/hub/session {"desiredCapabilities":{"platformName":"iOS","platformVersion":"8.1.2","browserName":"Safari","deviceName":"Milosz's iPad","autoWebview":true,"loggingPrefs":{"performance":"ALL"},"chromeOptions":{"args":["--disable-popup-blocking","--enable-gpu-benchmarking","--enable-thread-composting"]}}}
info: Client User-Agent string: undefined
info: [debug] The following desired capabilities were provided, but not recognized by appium. They will be passed on to any other services running on this server. : chromeOptions
info: [debug] Configuring Safari session
info: [debug] We're on iOS8+ so not copying mobile safari app
info: [debug] Creating new appium session 1c9fbe1c-0026-411a-b1a5-e50dbc674039
info: [debug] Removing any remaining instruments sockets
info: [debug] Cleaned up instruments socket /tmp/instruments_sock
info: [debug] Setting Xcode folder
info: [debug] Setting Xcode version
info: [debug] Setting iOS SDK Version
info: [debug] Getting sdk version from xcrun with a timeout
info: [debug] iOS SDK Version set to 8.1
info: [debug] Checking whether instruments supports our device string
info: [debug] Getting list of devices instruments supports
info: [debug] Instruments is at: /Applications/Xcode.app/Contents/Developer/usr/bin/instruments
info: [debug] Getting device string from opts: {"forceIphone":false,"forceIpad":false,"xcodeVersion":"6.1.1","iOSSDKVersion":"8.1","deviceName":"Milosz's iPad","platformVersion":"8.1.2"}
info: [debug] fixDevice is on
info: [debug] Final device string is: 'Milosz's iPad (8.1.2 Simulator)'
error: Could not find a device to launch. You requested 'Milosz's iPad (8.1.2 Simulator)', but the available devices were: ["iPad 2 (8.1 Simulator) [609B73F2-BF41-4BCC-91AE-C7C568C32528]","iPad Air (8.1 Simulator) [0365F058-7286-4F37-8903-9134B99BD3C9]","iPad Retina (8.1 Simulator) [56802605-7CC3-4979-B6C9-BAADBD4D84E3]","iPhone 4s (8.1 Simulator) [415BCB68-708E-4C34-A7E8-ED64DB94316D]","iPhone 5 (8.1 Simulator) [E6F7D9D4-A429-48FB-B9E0-0DE3A1B05A66]","iPhone 5s (8.1 Simulator) [6DB891D2-A1B9-4DE1-A7DE-175229D17857]","iPhone 6 (8.1 Simulator) [7A334B58-D325-40C2-ADE6-E87CD13B25F7]","iPhone 6 Plus (8.1 Simulator) [275FFC92-3DF4-453A-AA44-3254DA6B009B]"]
info: [debug] Cleaning up appium session
error: Failed to start an Appium session, err was: Error: Could not find a device to launch. You requested 'Milosz's iPad (8.1.2 Simulator)', but the available devices were: ["iPad 2 (8.1 Simulator) [609B73F2-BF41-4BCC-91AE-C7C568C32528]","iPad Air (8.1 Simulator) [0365F058-7286-4F37-8903-9134B99BD3C9]","iPad Retina (8.1 Simulator) [56802605-7CC3-4979-B6C9-BAADBD4D84E3]","iPhone 4s (8.1 Simulator) [415BCB68-708E-4C34-A7E8-ED64DB94316D]","iPhone 5 (8.1 Simulator) [E6F7D9D4-A429-48FB-B9E0-0DE3A1B05A66]","iPhone 5s (8.1 Simulator) [6DB891D2-A1B9-4DE1-A7DE-175229D17857]","iPhone 6 (8.1 Simulator) [7A334B58-D325-40C2-ADE6-E87CD13B25F7]","iPhone 6 Plus (8.1 Simulator) [275FFC92-3DF4-453A-AA44-3254DA6B009B]"]
info: [debug] Error: Could not find a device to launch. You requested 'Milosz's iPad (8.1.2 Simulator)', but the available devices were: ["iPad 2 (8.1 Simulator) [609B73F2-BF41-4BCC-91AE-C7C568C32528]","iPad Air (8.1 Simulator) [0365F058-7286-4F37-8903-9134B99BD3C9]","iPad Retina (8.1 Simulator) [56802605-7CC3-4979-B6C9-BAADBD4D84E3]","iPhone 4s (8.1 Simulator) [415BCB68-708E-4C34-A7E8-ED64DB94316D]","iPhone 5 (8.1 Simulator) [E6F7D9D4-A429-48FB-B9E0-0DE3A1B05A66]","iPhone 5s (8.1 Simulator) [6DB891D2-A1B9-4DE1-A7DE-175229D17857]","iPhone 6 (8.1 Simulator) [7A334B58-D325-40C2-ADE6-E87CD13B25F7]","iPhone 6 Plus (8.1 Simulator) [275FFC92-3DF4-453A-AA44-3254DA6B009B]"]
    at noDevicesError (/Users/hinok/.node/lib/node_modules/appium/lib/devices/ios/ios.js:1101:10)
    at null.<anonymous> (/Users/hinok/.node/lib/node_modules/appium/lib/devices/ios/ios.js:1107:16)
    at /Users/hinok/.node/lib/node_modules/appium/node_modules/async/lib/async.js:525:46
    at /Users/hinok/.node/lib/node_modules/appium/node_modules/async/lib/async.js:254:17
    at /Users/hinok/.node/lib/node_modules/appium/node_modules/async/lib/async.js:151:21
    at /Users/hinok/.node/lib/node_modules/appium/node_modules/async/lib/async.js:251:21
    at /Users/hinok/.node/lib/node_modules/appium/node_modules/async/lib/async.js:615:34
    at /Users/hinok/.node/lib/node_modules/appium/node_modules/async/lib/async.js:516:25
    at /Users/hinok/.node/lib/node_modules/appium/node_modules/appium-instruments/lib/instruments.js:111:7
    at ChildProcess.exithandler (child_process.js:645:7)
info: [debug] Responding to client with error: {"status":33,"value":{"message":"A new session could not be created. (Original error: Could not find a device to launch. You requested 'Milosz's iPad (8.1.2 Simulator)', but the available devices were: [\"iPad 2 (8.1 Simulator) [609B73F2-BF41-4BCC-91AE-C7C568C32528]\",\"iPad Air (8.1 Simulator) [0365F058-7286-4F37-8903-9134B99BD3C9]\",\"iPad Retina (8.1 Simulator) [56802605-7CC3-4979-B6C9-BAADBD4D84E3]\",\"iPhone 4s (8.1 Simulator) [415BCB68-708E-4C34-A7E8-ED64DB94316D]\",\"iPhone 5 (8.1 Simulator) [E6F7D9D4-A429-48FB-B9E0-0DE3A1B05A66]\",\"iPhone 5s (8.1 Simulator) [6DB891D2-A1B9-4DE1-A7DE-175229D17857]\",\"iPhone 6 (8.1 Simulator) [7A334B58-D325-40C2-ADE6-E87CD13B25F7]\",\"iPhone 6 Plus (8.1 Simulator) [275FFC92-3DF4-453A-AA44-3254DA6B009B]\"])","origValue":"Could not find a device to launch. You requested 'Milosz's iPad (8.1.2 Simulator)', but the available devices were: [\"iPad 2 (8.1 Simulator) [609B73F2-BF41-4BCC-91AE-C7C568C32528]\",\"iPad Air (8.1 Simulator) [0365F058-7286-4F37-8903-9134B99BD3C9]\",\"iPad Retina (8.1 Simulator) [56802605-7CC3-4979-B6C9-BAADBD4D84E3]\",\"iPhone 4s (8.1 Simulator) [415BCB68-708E-4C34-A7E8-ED64DB94316D]\",\"iPhone 5 (8.1 Simulator) [E6F7D9D4-A429-48FB-B9E0-0DE3A1B05A66]\",\"iPhone 5s (8.1 Simulator) [6DB891D2-A1B9-4DE1-A7DE-175229D17857]\",\"iPhone 6 (8.1 Simulator) [7A334B58-D325-40C2-ADE6-E87CD13B25F7]\",\"iPhone 6 Plus (8.1 Simulator) [275FFC92-3DF4-453A-AA44-3254DA6B009B]\"]"},"sessionId":null}
info: <-- POST /wd/hub/session 500 1182.399 ms - 1460 
info: --> DELETE /wd/hub/session {}
info: [debug] Trying to stop appium but there's no session, doing nothing
info: [debug] Responding to client with error: {"status":1,"value":{"message":"undefined status object"},"sessionId":null}
info: <-- DELETE /wd/hub/session 500 0.435 ms - 75 
[ {"message":"[quit()] Error response status: 1 Selenium error: undefined status object","status":1,"cause":{"status":1,"value":{"message":"undefined status object"},"sessionId":null}} ]

```

Other informations
- Xcode sees iPad in device screen (cmd + shift + 2 while xcode is opened)
- Appium is launched (appium &)
- I can run tests on iOS simulator
- appium-doctor says that everything is ok
```
sudo appium-doctor --ios
Password:
Running iOS Checks
✔ Xcode is installed at /Applications/Xcode.app/Contents/Developer
✔ Xcode Command Line Tools are installed.
✔ DevToolsSecurity is enabled.
✔ The Authorization DB is set up properly.
✔ Node binary found at /usr/local/bin/node
✔ iOS Checks were successful.

✔ All Checks were successful
```
- I turned on UI Automation on real iPad in Settings - Developer - Enable UI Automation
- I found in Appium FAQ, that I should authorize appium, so I also typed
```
sudo authorize_ios
```

If I specify udid in config.json
```
{
    "selenium": "http://localhost:4723/wd/hub",
	"browsers": [{
		"platformName": "iOS",
		"platformVersion": "8.1.2",
		"browserName": "Safari",
		"deviceName": "Milosz's iPad",
		"autoWebview": true,
		"loggingPrefs": {
			"performance": "ALL"
		},
        "udid": "my_udid_here"
	}]
}
```
I got another error
```
hinok at hinok in ~/Desktop/Dev/perfjankie on master [!?]
$ browser-perf --config-file=configs/ipad.config.json http://localhost:8000/admin/dashboard
info: --> POST /wd/hub/session {"desiredCapabilities":{"platformName":"iOS","platformVersion":"8.1.2","browserName":"Safari","deviceName":"Milosz's iPad","autoWebview":true,"loggingPrefs":{"performance":"ALL"},"uuid":"my_udid_here","forceIpad":true,"chromeOptions":{"args":["--disable-popup-blocking","--enable-gpu-benchmarking","--enable-thread-composting"]}}}
info: Client User-Agent string: undefined
info: [debug] The following desired capabilities were provided, but not recognized by appium. They will be passed on to any other services running on this server. : uuid, forceIpad, chromeOptions
info: [debug] Configuring Safari session
info: [debug] We're on iOS8+ so not copying mobile safari app
info: [debug] Creating new appium session 509d6e28-e21d-40e7-a1d9-fd103c58c4cc
info: [debug] Removing any remaining instruments sockets
info: [debug] Cleaned up instruments socket /tmp/instruments_sock
info: [debug] Setting Xcode folder
info: [debug] Setting Xcode version
info: [debug] Setting iOS SDK Version
info: [debug] Getting sdk version from xcrun with a timeout
info: [debug] iOS SDK Version set to 8.1
info: [debug] Checking whether instruments supports our device string
info: [debug] Getting list of devices instruments supports
info: [debug] Instruments is at: /Applications/Xcode.app/Contents/Developer/usr/bin/instruments
info: [debug] Getting device string from opts: {"forceIphone":false,"forceIpad":true,"xcodeVersion":"6.1.1","iOSSDKVersion":"8.1","deviceName":"Milosz's iPad","platformVersion":"8.1.2"}
info: [debug] fixDevice is on
info: [debug] Final device string is: 'Milosz's iPad (8.1.2 Simulator)'
error: Could not find a device to launch. You requested 'Milosz's iPad (8.1.2 Simulator)', but the available devices were: ["iPad 2 (8.1 Simulator) [609B73F2-BF41-4BCC-91AE-C7C568C32528]","iPad Air (8.1 Simulator) [0365F058-7286-4F37-8903-9134B99BD3C9]","iPad Retina (8.1 Simulator) [56802605-7CC3-4979-B6C9-BAADBD4D84E3]","iPhone 4s (8.1 Simulator) [415BCB68-708E-4C34-A7E8-ED64DB94316D]","iPhone 5 (8.1 Simulator) [E6F7D9D4-A429-48FB-B9E0-0DE3A1B05A66]","iPhone 5s (8.1 Simulator) [6DB891D2-A1B9-4DE1-A7DE-175229D17857]","iPhone 6 (8.1 Simulator) [7A334B58-D325-40C2-ADE6-E87CD13B25F7]","iPhone 6 Plus (8.1 Simulator) [275FFC92-3DF4-453A-AA44-3254DA6B009B]"]
info: [debug] Cleaning up appium session
error: Failed to start an Appium session, err was: Error: Could not find a device to launch. You requested 'Milosz's iPad (8.1.2 Simulator)', but the available devices were: ["iPad 2 (8.1 Simulator) [609B73F2-BF41-4BCC-91AE-C7C568C32528]","iPad Air (8.1 Simulator) [0365F058-7286-4F37-8903-9134B99BD3C9]","iPad Retina (8.1 Simulator) [56802605-7CC3-4979-B6C9-BAADBD4D84E3]","iPhone 4s (8.1 Simulator) [415BCB68-708E-4C34-A7E8-ED64DB94316D]","iPhone 5 (8.1 Simulator) [E6F7D9D4-A429-48FB-B9E0-0DE3A1B05A66]","iPhone 5s (8.1 Simulator) [6DB891D2-A1B9-4DE1-A7DE-175229D17857]","iPhone 6 (8.1 Simulator) [7A334B58-D325-40C2-ADE6-E87CD13B25F7]","iPhone 6 Plus (8.1 Simulator) [275FFC92-3DF4-453A-AA44-3254DA6B009B]"]
info: [debug] Error: Could not find a device to launch. You requested 'Milosz's iPad (8.1.2 Simulator)', but the available devices were: ["iPad 2 (8.1 Simulator) [609B73F2-BF41-4BCC-91AE-C7C568C32528]","iPad Air (8.1 Simulator) [0365F058-7286-4F37-8903-9134B99BD3C9]","iPad Retina (8.1 Simulator) [56802605-7CC3-4979-B6C9-BAADBD4D84E3]","iPhone 4s (8.1 Simulator) [415BCB68-708E-4C34-A7E8-ED64DB94316D]","iPhone 5 (8.1 Simulator) [E6F7D9D4-A429-48FB-B9E0-0DE3A1B05A66]","iPhone 5s (8.1 Simulator) [6DB891D2-A1B9-4DE1-A7DE-175229D17857]","iPhone 6 (8.1 Simulator) [7A334B58-D325-40C2-ADE6-E87CD13B25F7]","iPhone 6 Plus (8.1 Simulator) [275FFC92-3DF4-453A-AA44-3254DA6B009B]"]
    at noDevicesError (/Users/hinok/.node/lib/node_modules/appium/lib/devices/ios/ios.js:1101:10)
    at null.<anonymous> (/Users/hinok/.node/lib/node_modules/appium/lib/devices/ios/ios.js:1107:16)
    at /Users/hinok/.node/lib/node_modules/appium/node_modules/async/lib/async.js:525:46
    at /Users/hinok/.node/lib/node_modules/appium/node_modules/async/lib/async.js:254:17
    at /Users/hinok/.node/lib/node_modules/appium/node_modules/async/lib/async.js:151:21
    at /Users/hinok/.node/lib/node_modules/appium/node_modules/async/lib/async.js:251:21
    at /Users/hinok/.node/lib/node_modules/appium/node_modules/async/lib/async.js:615:34
    at /Users/hinok/.node/lib/node_modules/appium/node_modules/async/lib/async.js:516:25
    at /Users/hinok/.node/lib/node_modules/appium/node_modules/appium-instruments/lib/instruments.js:111:7
    at ChildProcess.exithandler (child_process.js:645:7)
info: [debug] Responding to client with error: {"status":33,"value":{"message":"A new session could not be created. (Original error: Could not find a device to launch. You requested 'Milosz's iPad (8.1.2 Simulator)', but the available devices were: [\"iPad 2 (8.1 Simulator) [609B73F2-BF41-4BCC-91AE-C7C568C32528]\",\"iPad Air (8.1 Simulator) [0365F058-7286-4F37-8903-9134B99BD3C9]\",\"iPad Retina (8.1 Simulator) [56802605-7CC3-4979-B6C9-BAADBD4D84E3]\",\"iPhone 4s (8.1 Simulator) [415BCB68-708E-4C34-A7E8-ED64DB94316D]\",\"iPhone 5 (8.1 Simulator) [E6F7D9D4-A429-48FB-B9E0-0DE3A1B05A66]\",\"iPhone 5s (8.1 Simulator) [6DB891D2-A1B9-4DE1-A7DE-175229D17857]\",\"iPhone 6 (8.1 Simulator) [7A334B58-D325-40C2-ADE6-E87CD13B25F7]\",\"iPhone 6 Plus (8.1 Simulator) [275FFC92-3DF4-453A-AA44-3254DA6B009B]\"])","origValue":"Could not find a device to launch. You requested 'Milosz's iPad (8.1.2 Simulator)', but the available devices were: [\"iPad 2 (8.1 Simulator) [609B73F2-BF41-4BCC-91AE-C7C568C32528]\",\"iPad Air (8.1 Simulator) [0365F058-7286-4F37-8903-9134B99BD3C9]\",\"iPad Retina (8.1 Simulator) [56802605-7CC3-4979-B6C9-BAADBD4D84E3]\",\"iPhone 4s (8.1 Simulator) [415BCB68-708E-4C34-A7E8-ED64DB94316D]\",\"iPhone 5 (8.1 Simulator) [E6F7D9D4-A429-48FB-B9E0-0DE3A1B05A66]\",\"iPhone 5s (8.1 Simulator) [6DB891D2-A1B9-4DE1-A7DE-175229D17857]\",\"iPhone 6 (8.1 Simulator) [7A334B58-D325-40C2-ADE6-E87CD13B25F7]\",\"iPhone 6 Plus (8.1 Simulator) [275FFC92-3DF4-453A-AA44-3254DA6B009B]\"]"},"sessionId":null}
info: <-- POST /wd/hub/session 500 1101.294 ms - 1460 
info: --> DELETE /wd/hub/session {}
info: [debug] Trying to stop appium but there's no session, doing nothing
info: [debug] Responding to client with error: {"status":1,"value":{"message":"undefined status object"},"sessionId":null}
info: <-- DELETE /wd/hub/session 500 0.403 ms - 75 
[ {"message":"[quit()] Error response status: 1 Selenium error: undefined status object","status":1,"cause":{"status":1,"value":{"message":"undefined status object"},"sessionId":null}} ]
```

I see that in Wiki page is written that there is possibility to run tests on real devices. Did I do something wrong?

**Comment by axemclion** [comment]
This looks like an appium issue. It may be quicker to isolate the issue and just try to run a scenario using appium alone. Can you try running a simple selenium test (say load a page, and print its title) using appium without browser-perf ?

**Comment by hinok** [comment]
I see that @scnymc had exactly very similiar issue like me with appium, more on https://github.com/appium/appium/issues/4198#issuecomment-65179542

Especially this fragment and fact that he also wanted run tests on iPad.
```
the page always stay on "Apple.com" which launched by SafariLauncher
```

I will try today evening run only appium with bypassing browser-perf.

**Comment by hinok** [comment]
Hey, appium works perfectly with this simple test. At the beginning SafariLauncher opens apple.com but after few seconds it opens also my defined page in test, in this case: http://github.com.

```
"use strict";

var wd = require('wd');
var chai = require('chai');
var chaiAsPromised = require('chai-as-promised');
var colors = require('colors');

chai.use(chaiAsPromised);
chai.should();
chaiAsPromised.transferPromiseness = wd.transferPromiseness;

var desired = {
  deviceName: 'Milosz\'s iPad',
  platformName: 'iOS',
  browserName: 'Safari',
  newCommandTimeout: 60
};

var browser = wd.promiseChainRemote('localhost' , 4723);

browser.on('status', function(info) {
  console.log('status:' + info.cyan);
});

browser.on('command', function(meth, path, data) {
  console.log('command > ' + meth.yellow, path.grey, data || '');
});

// Run the test
browser.chain()
  .then(function () {
    return browser.init(desired);
  })
  .get('http://github.com')
  .title()
  .should.become('GitHub · Build software better, together.')
  .sleep(5000)
  .quit()
  .catch(function (err) {
    console.log(err);
    throw err;
  })
  .done();
```

Output

```
command > CALL noop() 
command > RESPONSE noop() 
command > CALL init({"deviceName":"Milosz's iPad","platformName":"iOS","browserName":"Safari","newCommandTimeout":60}) 
status:
Driving the web on session: <myudid>

command > RESPONSE init({"deviceName":"Milosz's iPad","platformName":"iOS","browserName":"Safari","newCommandTimeout":60}) "<myudid>",null
command > CALL get("http://github.com") 
command > RESPONSE get("http://github.com") 
command > CALL title() 
command > RESPONSE title() "GitHub · Build software better, together."
command > CALL sleep(5000) 
command > RESPONSE sleep(5000) 
command > CALL quit() 
status:
Ending your web drivage..

command > RESPONSE quit() 
```

**Comment by Techies15** [comment]
hey guys, i need a small help in here ....My script is given below.Can someone help me out cos I'm facing the same issue where the page stay in "apple.com"....I am not able to open "m.ebay.in"


CODE:
public class CSmartWeb{

	public static RemoteWebDriver driver = null;
	private static Utils utils =null;
	@Test
	public void testCaseDefaultScnTsts() throws Exception {
	try{
		System.out.println("testing....");
		driver.get("https://m.ebay.in/");
		WebElement webElmt = null;		        
		//Iteration 0
		utils.createIteration();
		try{
		}catch(Exception e){ 
			 System.out.println("Exception: " + e.getLocalizedMessage()); 
		}

@BeforeClass
	public static void beforeMethod() throws MalformedURLException,InterruptedException{
		try{
		DesiredCapabilities capabilities = new DesiredCapabilities();

		capabilities.setCapability(MobileCapabilityType.DEVICE_NAME, "iPhone 5s");
		capabilities.setCapability(MobileCapabilityType.UDID,"5dd18b4aa36d4e295211af4c63403b959aed0547");

		capabilities.setCapability("browserName", "safari");
		capabilities.setCapability(MobileCapabilityType.VERSION, "8.2");
		capabilities.setCapability(MobileCapabilityType.PLATFORM_NAME, "iOS");

		try{
			driver = new IOSDriver(
					new URL("http://127.0.0.1:4723/wd/hub"), capabilities);
		}catch(Exception e){
			e.printStackTrace();
			}
	
		}catch(Exception e){
		e.printStackTrace();
		}
	}

**Comment by axemclion** [comment]
@Techies15 Could this be an issue with appium ?

**Comment by Techies15** [comment]
@axemclion I have tried this with appium version 1.4.8
Any solution or workaround for this??

**Comment by axemclion** [comment]
@Techies15 You mean this works with Appium ?

**Comment by knreddy036** [comment]
How to kill all the opened safari windows before launching safari browser on iPhone devices using appium
