### ISSUE TITLE
Problem starting browser-perf with Cordova app.

### ISSUE THREAD

**Issue by Darkoon** [axemclion/browser-perf#72]
Hello!
Following instructions from https://github.com/axemclion/browser-perf/wiki/Setup-Instructions#testing-mobile-cordova-webviewhybrid-applications I started ChromeDriver and then tried to start browser-perf with config: 
`{
    "selenium": "localhost:9515",
    "browsers": [{
        "browserName": "android",
        "chromeOptions": {
            "androidActivity": "com.me.MyApp.MainActivity",
            "androidPackage": "com.me.MyApp"
        }
    }]
}
`
My cordova application stated on connected mobile device, but after a while it crashed and browser-perf logged error:
`Error: [init({"browserName":"android","chromeOptions":{"androidActivity":"com.me.MyApp.MainActivity","androidPackage":"com.me.MyApp","perfLoggingPrefs":{"traceCategories":",blink.console,devtools.timeline,disabled-by-default-devtools.timeline,toplevel,disabled-by-default-devtools.timeline.frame"},"args":["--enable-gpu-benchmarking","--enable-thread-composting"]},"loggingPrefs":{"performance":"ALL"}})] The environment you requested was unavailable.
    at C:\Users\me\AppData\Roaming\npm\node_modules\browser-perf\node_modules\wd\lib\webdriver.js:129:15
    at Request._callback (C:\Users\me\AppData\Roaming\npm\node_modules\browser-perf\node_modules\wd\lib\http-utils.js:87:7)
    at Request.self.callback (C:\Users\me\AppData\Roaming\npm\node_modules\browser-perf\node_modules\wd\node_modules\request\request.js:368:22)
    at emitTwo (events.js:87:13)
    at Request.emit (events.js:172:7)
    at Request.<anonymous> (C:\Users\me\AppData\Roaming\npm\node_modules\browser-perf\node_modules\wd\node_modules\request\request.js:1219:14)
    at emitOne (events.js:82:20)
    at Request.emit (events.js:169:7)
    at IncomingMessage.<anonymous> (C:\Users\me\AppData\Roaming\npm\node_modules\browser-perf\node_modules\wd\node_modules\request\request.js:1167:12)
    at emitNone (events.js:72:20)
`
I want to do some performance test of my cordova application, unfortunately there are very few tools to use. How can I fix this problem and successfully start browser-perf?

**Comment by axemclion** [comment]
Are you able to run selenium with Cordova ?

**Comment by Darkoon** [comment]
I tried to set up selenium and passing it's socket to config, but still it fails to do anything. Description above is connected with your setup instructions.

**Comment by axemclion** [comment]
The error is here "The environment you requested was unavailable". You don't need full selenium, Chromedriver should do. We need a way to see if we can connect chromedriver and do stuff with Cordova. Only if ChromeDriver can attach to the app can browser-perf even kick in.

Are you able to connect to the webview using chrome dev tools ?

**Comment by Darkoon** [comment]
I added chromeDriver localization in PATH and managed to try running browser-perf with android emulator. Result was pretty similar to the last posted one (app started but crashed after a while), but this time logs were different:
```
Error: [log("performance")] Error response status: 13, , UnknownError - An unknown server-side error occurred while processing the command. Selenium error: unknown error: session deleted because error encountered when notifying listeners of 'GetLog' command
from unknown error: unexpected command response
  (Session info: webview=39.0.0.0)
  (Driver info: chromedriver=2.24.417431 (9aea000394714d2fbb20850021f6204f2256b9cf),platform=Windows NT 6.3.9600 x86_64)
    at exports.newError (C:\Users\local\AppData\Roaming\npm\node_modules\browser-perf\node_modules\wd\lib\utils.js:139:13)
    at C:\Users\local\AppData\Roaming\npm\node_modules\browser-perf\node_modules\wd\lib\callbacks.js:75:19
    at C:\Users\local\AppData\Roaming\npm\node_modules\browser-perf\node_modules\wd\lib\webdriver.js:174:5
    at Request._callback (C:\Users\local\AppData\Roaming\npm\node_modules\browser-perf\node_modules\wd\lib\http-utils.js:87:7)
    at Request.self.callback (C:\Users\local\AppData\Roaming\npm\node_modules\browser-perf\node_modules\wd\node_modules\request\request.js:368:22)
    at emitTwo (events.js:87:13)
    at Request.emit (events.js:172:7)
    at Request.<anonymous> (C:\Users\local\AppData\Roaming\npm\node_modules\browser-perf\node_modules\wd\node_modules\request\request.js:1219:14)
    at emitOne (events.js:82:20)
    at Request.emit (events.js:169:7)

```

Answering your question: Yes I can access webview of emulated app and app on my mobile device. There are no problems with chrome dev tools.

**Comment by axemclion** [comment]
For the error above, can you send me the exact set of capabilities that were sent to Chromedriver ? for more information, you could set and environment variable called `export DEBUG=*`.

**Comment by Darkoon** [comment]
All I was able to do is get logs from chromedriver. After a try it generated nearly 8k lines of logs with some specific action listed. I don't know which piece of it will be usefull to solve problem. Lines connected with error:
`[716.568][DEBUG]: Sending adb command: host:transport:emulator-5554|shell:am force-stop com.me.MyApp
[716.893][DEBUG]: Received adb response: 
[716.893][SEVERE]: unknown error: session deleted because error encountered when notifying listeners of 'GetLog' command
from unknown error: unexpected command response
  (Session info: webview=39.0.0.0)
[716.893][DEBUG]: Log type 'driver' lost 1 entries on destruction
[716.893][DEBUG]: Log type 'performance' lost 169 entries on destruction
[716.893][DEBUG]: Log type 'browser' lost 2 entries on destruction`

**Comment by axemclion** [comment]
@Darkoon Were you able to resolve this issue ? I tried running a Cordova app, and it seems like it was working for me.

**Comment by axemclion** [comment]
Closing this issue since there is no repro. If you are still having this issue, please reopen the issue and I will be glad to help you.
