### ISSUE TITLE
namespace.charCodeAt is not a function

### ISSUE THREAD

**Issue by pedro93** [axemclion/browser-perf#77]
Hello, 
I was attempting to test this project but got the following error after installing everything.

```
$ browser-perf --selenium=http://localhost:4444/wd/hub --browsers=chrome http://google.com
(node:38250) DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.
/usr/local/lib/node_modules/browser-perf/node_modules/q/q.js:155
                throw e;
                ^

TypeError: namespace.charCodeAt is not a function
    at selectColor (/usr/local/lib/node_modules/browser-perf/node_modules/debug/src/debug.js:48:46)
    at createDebug (/usr/local/lib/node_modules/browser-perf/node_modules/debug/src/debug.js:120:17)
    at require.browsers (/usr/local/lib/node_modules/browser-perf/lib/cli.js:37:3)
    at /usr/local/lib/node_modules/browser-perf/lib/index.js:31:3
    at _fulfilled (/usr/local/lib/node_modules/browser-perf/node_modules/q/q.js:834:54)
    at self.promiseDispatch.done (/usr/local/lib/node_modules/browser-perf/node_modules/q/q.js:863:30)
    at Promise.promise.promiseDispatch (/usr/local/lib/node_modules/browser-perf/node_modules/q/q.js:796:13)
    at /usr/local/lib/node_modules/browser-perf/node_modules/q/q.js:604:44
    at runSingle (/usr/local/lib/node_modules/browser-perf/node_modules/q/q.js:137:13)
    at flush (/usr/local/lib/node_modules/browser-perf/node_modules/q/q.js:125:13)
```

I am running a local selenium hub instance (v3.0.1) accessible at http://localhost:4444/wd/hub
Node version: v7.4.0
OS: El Capitan (10.11.6)

Thanks for taking the time to read this :)

**Comment by axemclion** [comment]
@pedro93 Thanks for reaching out and submitting the bug. We already log the error, so I guess we can remove [this statement](https://github.com/axemclion/browser-perf/blob/master/lib/cli.js#L37)

**Comment by agusbosso** [comment]
@axemclion I obtained the same error running with selenium hub instance in MAC, node version v4.2.3:

/Users/agustinabosso/.nvm/versions/node/v4.2.3/lib/node_modules/browser-perf/node_modules/q/q.js:155
                throw e;
                ^

TypeError: namespace.charCodeAt is not a function
    at selectColor (/Users/agustinabosso/.nvm/versions/node/v4.2.3/lib/node_modules/browser-perf/node_modules/debug/src/debug.js:48:46)
    at createDebug (/Users/agustinabosso/.nvm/versions/node/v4.2.3/lib/node_modules/browser-perf/node_modules/debug/src/debug.js:120:17)
    at require.browsers (/Users/agustinabosso/.nvm/versions/node/v4.2.3/lib/node_modules/browser-perf/lib/cli.js:37:3)
    at /Users/agustinabosso/.nvm/versions/node/v4.2.3/lib/node_modules/browser-perf/lib/index.js:31:3
    at _fulfilled (/Users/agustinabosso/.nvm/versions/node/v4.2.3/lib/node_modules/browser-perf/node_modules/q/q.js:854:54)
    at self.promiseDispatch.done (/Users/agustinabosso/.nvm/versions/node/v4.2.3/lib/node_modules/browser-perf/node_modules/q/q.js:883:30)
    at Promise.promise.promiseDispatch (/Users/agustinabosso/.nvm/versions/node/v4.2.3/lib/node_modules/browser-perf/node_modules/q/q.js:816:13)
    at /Users/agustinabosso/.nvm/versions/node/v4.2.3/lib/node_modules/browser-perf/node_modules/q/q.js:624:44
    at runSingle (/Users/agustinabosso/.nvm/versions/node/v4.2.3/lib/node_modules/browser-perf/node_modules/q/q.js:137:13)
    at flush (/Users/agustinabosso/.nvm/versions/node/v4.2.3/lib/node_modules/browser-perf/node_modules/q/q.js:125:13)

**Comment by kohlmannj** [comment]
I'm also seeing this error after installing with `yarn global add browser-perf` on Node v6.11.0 / macOS 10.12.5.
