### ISSUE TITLE
Unsupported OS/browser/version/device combo

### ISSUE THREAD

**Issue by premkh9** [axemclion/browser-perf#81]
Hi Ram,

I am using below capabilities to test the perf in saucelabs. But I am seeing proper response, when I suppress platform, screenresolution and version details. Not sure why I am observing starnge message when these options are added . Also I am not seeing 'number of requests' stats 

    capabilities: {
        'browserName': 'chrome',
		'platform': 'Windows 7',
		'screenResolution':'1920x1200',
		'version':'51.0',
		'name': 'Protractor Chrome Job',
    },

    selenium: 'http://ondemand.saucelabs.com',

**Error details -** 

[14:30:02] E/launcher - Unsupported OS/browser/version/device combo: OS: 'Windows 2003', Browser: 'googlechrome', Version: '51.0.', Device: 'unspecified', Screen Resolution: '1920x1200'
[14:30:02] E/launcher - UnsupportedOperationError: Unsupported OS/browser/version/device combo: OS: 'Windows 2003', Browser: 'googlechrome', Version: '51.0.', Device: 'unspecified', Screen Resolution: '1920x1200'
    at WebDriverError (C:\Users\pkashipa\AppData\Roaming\npm\node_modules\protractor-perf\node_modules\protractor\node_modules\selenium-webdriver\lib\error.js:27:10)
    at UnsupportedOperationError (C:\Users\pkashipa\AppData\Roaming\npm\node_modules\protractor-perf\node_modules\protractor\node_modules\selenium-webdriver\lib\error.js:448:10)
    at parseHttpResponse (C:\Users\pkashipa\AppData\Roaming\npm\node_modules\protractor-perf\node_modules\protractor\node_modules\selenium-webdriver\http\index.js:552:11)
    at C:\Users\pkashipa\AppData\Roaming\npm\node_modules\protractor-perf\node_modules\protractor\node_modules\selenium-webdriver\http\index.js:472:11
    at ManagedPromise.invokeCallback_ (C:\Users\pkashipa\AppData\Roaming\npm\node_modules\protractor-perf\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:1379:14)
    at TaskQueue.execute_ (C:\Users\pkashipa\AppData\Roaming\npm\node_modules\protractor-perf\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:2913:14)
    at TaskQueue.executeNext_ (C:\Users\pkashipa\AppData\Roaming\npm\node_modules\protractor-perf\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:2896:21)
    at C:\Users\pkashipa\AppData\Roaming\npm\node_modules\protractor-perf\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:2820:25
    at C:\Users\pkashipa\AppData\Roaming\npm\node_modules\protractor-perf\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:639:7
    at process._tickCallback (node.js:369:9)
From: Task: WebDriver.createSession()
    at Function.createSession (C:\Users\pkashipa\AppData\Roaming\npm\node_modules\protractor-perf\node_modules\protractor\node_modules\selenium-webdriver\lib\webdriver.js:329:24)
    at Builder.build (C:\Users\pkashipa\AppData\Roaming\npm\node_modules\protractor-perf\node_modules\protractor\node_modules\selenium-webdriver\builder.js:458:24)
    at Sauce.DriverProvider.getNewDriver (C:\Users\pkashipa\AppData\Roaming\npm\node_modules\protractor-perf\node_modules\protractor\built\driverProviders\driverProvider.js:37:33)
    at Runner.createBrowser (C:\Users\pkashipa\AppData\Roaming\npm\node_modules\protractor-perf\node_modules\protractor\built\runner.js:198:43)
    at C:\Users\pkashipa\AppData\Roaming\npm\node_modules\protractor-perf\node_modules\protractor\built\runner.js:277:30
    at _fulfilled (C:\Users\pkashipa\AppData\Roaming\npm\node_modules\protractor-perf\node_modules\protractor\node_modules\q\q.js:834:54)
    at self.promiseDispatch.done (C:\Users\pkashipa\AppData\Roaming\npm\node_modules\protractor-perf\node_modules\protractor\node_modules\q\q.js:863:30)
    at Promise.promise.promiseDispatch (C:\Users\pkashipa\AppData\Roaming\npm\node_modules\protractor-perf\node_modules\protractor\node_modules\q\q.js:796:13)
    at C:\Users\pkashipa\AppData\Roaming\npm\node_modules\protractor-perf\node_modules\protractor\node_modules\q\q.js:556:49
    at runSingle (C:\Users\pkashipa\AppData\Roaming\npm\node_modules\protractor-perf\node_modules\protractor\node_modules\q\q.js:137:13)
[14:30:02] E/launcher - Process exited with error code 199

**Comment by axemclion** [comment]
Are you able to use selenium directly with these parameters ?

**Comment by premkh9** [comment]
Sorry I didnt get your question. I spoke to saucelabs support as well. They said, its beyond thr control and they are not sure about the issue. If I just pass chrome browser without platform and version details, by default, it will be executed in windows XP and chrome 49 version. But I need to execute in latest version of chrome. 

https://saucelabs.com/beta/tests/d1075bea739448d0af2ca6b089ca2cfb/metadata#5

In above logs, it says device as unspecified. DOnt know, why its expecting device details.

**Comment by axemclion** [comment]
Instead of running browser-perf, can you try using the `wd` node module and run that with the parameters on saucelabs ? 

Also the list to the test is not publicly accessible.

**Comment by premkh9** [comment]
sorry please close down this issue. It was supposed to be reported under protractor-perf.
